### ISSUE TITLE
Silex ~1.1 compatibility

### ISSUE THREAD

**Issue by peschee** [umpirsky/I18nRoutingServiceProvider#1]
Hi

Currently, your routing service provider is compatible with `1.0.*` only. Any chance you are going to make it `~1.1` compatible?

Regards
Peter

**Comment by umpirsky** [comment]
Hi.

Not sure when I will have time to do it. But I will be happy to merge PR. Thanks.

**Comment by peschee** [comment]
Resolved in #2
